before:
  hooks:
    - go mod tidy

builds:

- main: cmd/venus/main.go
  binary: venus
  id: venus

  env:
  - CGO_ENABLED=0

  goos: [windows,linux,darwin]
  goarch: [amd64,386,arm,arm64]
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64

  flags:
    - -trimpath

archives:
- format: zip
  id: venus
  builds: [venus]
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256

announce:
  slack:
    enabled: true
    channel: '#release'
    username: GoReleaser
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}' 
